name: figma
description: A Figma API wrapper library for interacting with Figma documents, written in pure Dart.
version: 2.0.1
homepage: https://github.com/dnb-asa/figma
repository: https://github.com/dnb-asa/figma
issue_tracker: https://github.com/dnb-asa/figma/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http2: ^1.0.1
  json_annotation: ^3.0.1
  equatable: ^1.2.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  dotenv: ^2.0.0
