name: figma
description: A Figma API wrapper library written in Dart.
version: 1.0.0+2
homepage: https://github.com/dnb-asa/figma
repository: https://github.com/dnb-asa/figma
issue_tracker: https://github.com/dnb-asa/figma/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  equatable: ^1.1.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  dotenv: ^2.0.0
